### PR TITLE
WIP: Update for new API

### PR DESCRIPTION
**Pull request by matthieugomez**
I'm trying to update for the new `DataRead` API. I'm stuck at the `handle_value` function : the `value` argument is passed by value in the C code and I'm not sure how to create a new structure in Julia to mirror the C structure.

### CODE REVIEW

**Comment by evanmiller** [comment]
Yeah the pass-by-value issue tripped me up too... happy to merge if you get it figured out.

**Comment by matthieugomez** [comment]
I've just reorganized the code a little bit even though it still does not solve the issue.

- For the passing by value, it's not really clear what it supported right now in Julia. It seems that one should define a `immutable` type mirroring the C type. One issue is the union field. The idea is to define the field with the type of the the largest possible type (a `Cdouble`) and reinterpret it depending on the value of `readtat_types_t`. However, it does not seem to work (as you can see in `@show value.v` etc...

- Beyond the pass by value issue, unsafe_pointer_to_objref(ctx_ptr)::DataReadCtx fails when called inside `handle_value` (while it works in `handle_variable`). Do you have any idea why? Is it linked to the pass by value of `value` in the same function or it is something completely different?

**Comment by evanmiller** [comment]
Sorry -- I have no clue on either of these issues :-/. Might be worth bringing in a Julia expert to pitch in.

**Comment by matthieugomez** [comment]
It works now.  I could not get readstat_value_type to work though, so I rely on the column type rather than the value.type. Is it an issue going forward?
FYI, it's twice as slow as the R implementation for a .dta file (the only case I tested).

**Comment by evanmiller** [comment]
Great, I'll get it merged in. Column type is fine.

Are you comparing to R's foreign package or to haven? I know foreign is quite fast. (It's written in C without callbacks.)

**Comment by matthieugomez** [comment]
haven on a 300MB file

**Comment by evanmiller** [comment]
Interesting. I'd have to profile to find the difference. Haven is written in C++ so it's not too surprising.

**Pull request merged**
